### ISSUE TITLE
Cannot run a new revel application

### ISSUE THREAD

**Issue by spokzers** [revel/revel#1373]
Created a new revel application following the tutorial from the [website](https://revel.github.io/tutorial/gettingstarted.html).

successfully managed to run `revel new -a myapp`
but when I do `revel run -a myapp` I get the following errors

```
Revel executing: run a Revel application
ERROR 22:16:07 revel_container.go:214: Failed to load module.  Import of path failed modulePath=github.com/revel/modules/static error="cannot find package \"github.com/revel/modules/static\" in any of:\n\t/usr/local/go/src/github.com/revel/modules/static (from $GOROOT)\n\t/home/spokzers/go_workspace/src/github.com/revel/modules/static (from $GOPATH)"
ERROR 22:16:07 revel_container.go:214: Failed to load module.  Import of path failed modulePath=github.com/revel/modules/testrunner error="cannot find package \"github.com/revel/modules/testrunner\" in any of:\n\t/usr/local/go/src/github.com/revel/modules/testrunner (from $GOROOT)\n\t/home/spokzers/go_workspace/src/github.com/revel/modules/testrunner (from $GOPATH)"
WARN  22:16:07 harness.go:175: No http.addr specified in the app.conf listening on localhost interface only. This will not allow external access to your application
ERROR 22:16:08  revel module.go:163: Failed to load module.  Import of path failed  section=module modulePath=github.com/revel/modules/static error="cannot find package \"github.com/revel/modules/static\" in any of:\n\t/usr/local/go/src/github.com/revel/modules/static (from $GOROOT)\n\t/home/spokzers/go_workspace/src/github.com/revel/modules/static (from $GOPATH)"
ERROR 22:16:08  revel module.go:163: Failed to load module.  Import of path failed  section=module modulePath=github.com/revel/modules/testrunner error="cannot find package \"github.com/revel/modules/testrunner\" in any of:\n\t/usr/local/go/src/github.com/revel/modules/testrunner (from $GOROOT)\n\t/home/spokzers/go_workspace/src/github.com/revel/modules/testrunner (from $GOPATH)"
INFO  22:16:08    app     run.go:29: Running revel server
CRIT  22:16:08  revel logger.go:195: NewRoute: Failed to find controller for route path action /public/*filepath?Static.Serve
map[string]*revel.ActionPathData{"app.index":(*revel.ActionPathData)(0xc000248850), "app\\app.index":(*revel.ActionPathData)(0xc000248850)}
  section=router
CRIT  22:16:08  revel  server.go:66: Recovered error in startup                error="NewRoute: Failed to find controller for route path action /public/*filepath?Static.Serve \nmap[string]*revel.ActionPathData{\"app.index\":(*revel.ActionPathData)(0xc000248850), \"app\\\\app.index\":(*revel.ActionPathData)(0xc000248850)}\n"
panic: NewRoute: Failed to find controller for route path action /public/*filepath?Static.Serve
map[string]*revel.ActionPathData{"app.index":(*revel.ActionPathData)(0xc000248850), "app\\app.index":(*revel.ActionPathData)(0xc000248850)}
 [recovered]
        panic: Fatal error in startup

goroutine 1 [running]:
github.com/revel/revel.Run.func1()
        /home/spokzers/go_workspace/src/github.com/revel/revel/server.go:68 +0x151
panic(0x847020, 0xc00020bf90)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/revel/revel/logger.(*RevelLogger).Panic(0xc00008d020, 0xc00024c0f0, 0xe6, 0x0, 0x0, 0x0)
        /home/spokzers/go_workspace/src/github.com/revel/revel/logger/logger.go:207 +0xaf
github.com/revel/revel/logger.(*RevelLogger).Panicf(0xc00008d020, 0x90e487, 0x42, 0xc0002860e0, 0x2, 0x2)
        /home/spokzers/go_workspace/src/github.com/revel/revel/logger/logger.go:195 +0x8a
github.com/revel/revel.NewRoute(0xc8d640, 0xc000270152, 0x3, 0xc00027015a, 0x11, 0xc000270182, 0xc, 0xc00027018f, 0x8, 0xc000099e40, ...)
        /home/spokzers/go_workspace/src/github.com/revel/revel/router.go:145 +0xd8d
github.com/revel/revel.parseRoutes(0xc8d640, 0xc000099e40, 0x31, 0x0, 0x0, 0xc000270000, 0x34e, 0x1, 0x0, 0x0, ...)
        /home/spokzers/go_workspace/src/github.com/revel/revel/router.go:490 +0x3fe
github.com/revel/revel.parseRoutesFile(0xc8d640, 0xc000099e40, 0x31, 0x0, 0x0, 0xc0001c1d01, 0x40db38, 0x40, 0x8b1460, 0x8cfb01)
        /home/spokzers/go_workspace/src/github.com/revel/revel/router.go:436 +0x1a3
github.com/revel/revel.(*Router).Refresh(0xc00025d000, 0xc00025d000)
        /home/spokzers/go_workspace/src/github.com/revel/revel/router.go:250 +0x6a
github.com/revel/revel.init.5.func1()
        /home/spokzers/go_workspace/src/github.com/revel/revel/router.go:836 +0x139
github.com/revel/revel.runStartupHooks()
        /home/spokzers/go_workspace/src/github.com/revel/revel/server.go:131 +0x96
github.com/revel/revel.InitServer()
        /home/spokzers/go_workspace/src/github.com/revel/revel/server.go:37 +0x2e
github.com/revel/revel.Run(0xa39f)
        /home/spokzers/go_workspace/src/github.com/revel/revel/server.go:74 +0xe0
myapp/app/tmp/run.Run(0xa39f)
        /home/spokzers/go_workspace/src/myapp/app/tmp/run/run.go:24 +0x30
main.main()
        /home/spokzers/go_workspace/src/myapp/app/tmp/main.go:24 +0x81
ERROR 22:16:08 harness.go:231: Could not start application              error="revel/harness: app died reason: exit status 2"

```

what could be the problem ?
TIA

**Comment by notzippy** [comment]
If you run `go get github.com/revel/modules` does it work ?

**Comment by spokzers** [comment]
It did give me a 
```
can't load package: package github.com/revel/modules: no Go files in /home/spokzers/go_workspace/src/github.com/revel/modules
```
But when I did `revel run -a myapp`, it does work
Thanks

**Comment by notzippy** [comment]
That error is expected - when you fetch the modules repo by itself - but it is an issue with the revel/cmd that it doesn't auto-fetch the revel/modules package now. Ill leave this open until that is fixed.

**Comment by dropski** [comment]
I still have a problem to run my app, same errors as above. Any idea how to run it?

**Comment by notzippy** [comment]
It looks like you have an older version of revel/revel. Please update it
and revel/modules with go get -u command

**Comment by dropski** [comment]
It not help, but I figured it out, you have to create some new revel project `revel new some_project` and after that everything works fine with other projects - weird but helps
And about version, I have latest.

**Comment by gourlaa** [comment]
Same for us

**Comment by notzippy** [comment]
This is fixed now

**Comment by eenagy** [comment]
This is still a bug with the latest dependencies.

**Comment by xiuluo211314** [comment]
I get the same error with you, i used the latest version, but still get this error, is there solution ?Thanks
`
WARN  06:44:29 source_info.go:102: Type found in package: controllers, but did not embed from: revel.Controller name=DragNotebooksInfo importpath=github.com/leanote/leanote/app/controllers foundstructures=BaseController,Static,Captcha,Attach,Tag,Index,Auth,Album,File,Share,Notebook,User,Blog,NoteContentHistory,Note,AdminBaseController,ApiBaseContrller,MemberBaseController,Preview,AdminUpgrade,AdminBlog,Admin,AdminEmail,AdminUser,AdminData,AdminSetting,ApiNote,ApiUser,ApiNotebook,ApiFile,ApiAuth,ApiTag,MemberIndex,MemberUser,MemberBlog,MemberGroup,
DEBUG 06:44:31  revel  server.go:27: RegisterServerEngine: Registered engine   section=server name=go
INFO  06:44:31    app  revel.go:170: app.conf: No mode found: {"mode":"dev", "specialUseFlag":[]}  section=system
Revel proxy is listening, point your browser to : 9000
ERROR 06:44:31 harness.go:233: Could not start application              error="revel/harness: app died reason: exit status 1"
^Z
`

**Comment by ptman** [comment]
app.conf: No mode found: {"mode":"dev"

your app.conf doesn't seem to have a section called `[dev]` and fails to run in the default "dev" mode because of that. what sections do you have defined? `revel run appname prod` ?

**Comment by pedromorgan** [comment]
@notzippy quick silly questions.. is there a way to make revel.cmd detect version conflicts and also can the revel tool do an update eg `revel check` to check and `revel upgrade` to upgrade ?

**Comment by notzippy** [comment]
I added that to the last release, if it detects an incompatible framework
it will report and halt

**Comment by notzippy** [comment]
Rather it is on develop branch ATM, will be in next release

**Comment by extems** [comment]
Hello! Two years later someone got the same problem again.
userX:~/go$ revel run -a revelproject
Revel executing: run a Revel application
Downloading related packages ... completed.
ERROR 11:49:25  revel.go:107: Unable to execute                        error="Revel paths[error Failed to load module.  Import of path failed modulePath:github.com/revel/modules/static error:No files found in import path github.com/revel/modules/static ]"

**Comment by parochi** [comment]
I am not sure how solid is the framework when the given instructions does not work.

**Comment by notzippy** [comment]
@parochi This is a closed issue, there is an open issue on go1.6 build issues here #1528 which is being worked on.

**Comment by Anusha-Mandya-Krishna** [comment]
ERROR 13:40:28  revel.go:113: Unable to execute                        error="Revel paths[error app.conf: not found run-mode myapp]"
what could be the issuse?
